### PR TITLE
Add vulnerability form link

### PR DESCRIPTION
**Pull request by TomWFox**
As per https://github.com/parse-community/parse-server/pull/7081

### CODE REVIEW

**Comment by mtrezza** [comment]
Oh, what is the difference between the SECURITY.md of Parse Server and of .github? I though there was only 1 file for all repos?

**Review by mtrezza — APPROVED** [review]

**Comment by TomWFox** [comment]
This one is used by all repos, except those which have a SECURITY.md file. As Parse Server has it's own it doesn't inherit the `.github` one - the same principle applies to all the files in this repo.

We could remove the PS one, the only slight benefit I see from keeping it is that if you go looking for it in the files it is there to find, whereas when using the `.github` one its only visible in parts of the GitHub UI.

**Comment by mtrezza** [comment]
I see, so also when cloning the PS repo, the security file is currently included, but it would not be included if we only have the .github security file? If that is the case, then -  even though I'm not a fan of duplicates - maybe we should keep it in PS?

Or add a `SECURITY.TXT` file to the PS repo that contains just a text link to the securities page on github?

**Comment by TomWFox** [comment]
exactly, I think as it's the most popular and *most* important repo I think the duplication is worth it.

> Or add a SECURITY.TXT file to the PS repo that contains just a text link to the securities page on github?

Could do, personally I would leave it but don't really mind.

**Comment by mtrezza** [comment]
Then I'm fine with leaving it too.

**Pull request merged**
